name: crud_exemplo_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  intl: ^0.18.1
  provider: ^6.0.5
  uuid: ^4.0.0
  image_picker: ^0.8.4+1
  path_provider: ^2.0.4
  logging: ^1.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

